# parameters configuration
mode: train
root: data/
predefined_dataset: BreastCancerDataset
classes: ["malignant", "benign"]
max_samples: null
batch_size: 32
num_workers: 0
device: cuda
lr: 1e-3
model_name: src/SelfDefinedModel.py
in_features: 30
loss_function_name: BCEWithLogitsLoss
checkpoint_path: null
seed: 0
early_stopping: True
patience: 3
default_root_dir: save/
gpus: 1
precision: 32
max_epochs: 100
tuning_test: False
cpu_resources_per_trial: 1
gpu_resources_per_trial: 1
num_samples: 100

# transforms configuration
transforms_config:
  train: null

  val: null

  test: null

  predict: null

# target transforms configuration
target_transforms_config:
  train:
    OneHotEncoder:
      num_classes: null

  val:
    OneHotEncoder:
      num_classes: null

  test:
    OneHotEncoder:
      num_classes: null

  predict:
    OneHotEncoder:
      num_classes: null

# optimizers configuration
optimizers_config:
  Adam:
    betas:
      - 0.9
      - 0.999
    eps: 1e-08
    weight_decay: 0
    amsgrad: False

# learning rate schedulers configuration
lr_schedulers_config:
  CosineAnnealingLR:
    T_max: 10

# hyperparameter space configuration
hyperparameter_space_config:
  lr:
    uniform:
      lower: 1e-4
      upper: 1e-1

  max_epochs:
    randint:
      lower: 10
      upper: 200
