# parameters configuration
mode: train
root: data/
predefined_dataset: BreastCancerDataset
classes: ["malignant", "benign"]
max_samples: null
batch_size: 32
num_workers: 0
device: cuda
lr: 1e-3
model_name: src/SelfDefinedModel.py
in_features: 30
loss_function_name: BCEWithLogitsLoss
checkpoint_path: null

# transforms configuration
transforms_config:
  train: null

  val: null

  test: null

  predict: null

# target transforms configuration
target_transforms_config:
  train:
    LabelSmoothing:
      alpha: 0.2
      num_classes: null

  val:
    OneHotEncoder:
      num_classes: null

  test:
    OneHotEncoder:
      num_classes: null

  predict:
    OneHotEncoder:
      num_classes: null

# optimizers configuration
optimizers_config:
  Adam:
    betas:
      - 0.9
      - 0.999
    eps: 1e-08
    weight_decay: 0
    amsgrad: False

# learning rate schedulers configuration
lr_schedulers_config:
  CosineAnnealingLR:
    T_max: 10
